create table if not exists public.app_users (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  password_hash text not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

create unique index if not exists idx_app_users_username_lower
  on public.app_users ((lower(username)));

create table if not exists public.app_sessions (
  token text primary key,
  user_id uuid not null references public.app_users (id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_app_sessions_user_id on public.app_sessions (user_id);
create index if not exists idx_app_sessions_expires_at on public.app_sessions (expires_at);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.app_users (id) on delete cascade,
  title text not null default 'Yeni Sohbet',
  created_at timestamptz not null default now()
);

create index if not exists idx_conversations_user_id on public.conversations (user_id);
create index if not exists idx_conversations_created_at on public.conversations (created_at desc);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations (id) on delete cascade,
  sender_type text not null check (sender_type in ('user', 'admin')),
  content text not null check (char_length(content) > 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_messages_conversation_id on public.messages (conversation_id);
create index if not exists idx_messages_created_at on public.messages (created_at desc);

insert into public.app_users (username, password_hash, role)
values (
  'admin',
  'scrypt$7e3554ae5f91a70a71f2316ebb45d19a$db289bd20bfa8fb931cfa95ef0034b6a3e3e7a5a7e1e2841b2233152d5a13dfbb50e002fd49d759fee0b9488dd18c2a46977fe37ffa070da83264dcc667b655e',
  'admin'
)
on conflict ((lower(username)))
do update set
  password_hash = excluded.password_hash,
  role = 'admin';

-- Onceki eski tablolarin kalmasi sorun olmaz, ama istersen temizleyebilirsin:
-- drop table if exists public.user_roles cascade;
-- drop table if exists public.profiles cascade;
